FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# pytest и coverage
RUN pip install pytest pytest-asyncio pytest-cov

CMD ["pytest", "--asyncio-mode=auto", "--cov=app", "--cov-report=term"]
